### ISSUE TITLE
[Hacken 2022-11-25 High #1] Denial of Service Vulnerability

### ISSUE THREAD

**Issue by zhongfu** [suberra/funnel-contracts#30]
The internal function `_remainingAllowance()` will revert with overflow in situations where the `approveRenewable()` or `permitRenewable()` functions will be used to approve a max uint256 value with a `recoveryRate > 0`.

The overflow can occur with different edge cases:
```
approveRenewable(, type(uint256).max - type(uint192).max + 1, type(uint192).max)
```
```
approveRenewable(, type(uint256).max - type(uint64).max + 1, type(uint64).max)
```

The `_remainingAllowance()` function is used by `allowance()` and `transferFrom()`. These functions will be unusable after such approval.

## Path

./src/Funnel.sol: allowance(), _remainingAllowance(), transferFrom()

## Recommendation

Rewrite the logic to prevent overflows.

## Status
New

**Comment by zlace0x** [comment]
![image](https://user-images.githubusercontent.com/81418809/205632727-c039c1b5-4074-4f8a-bfe9-d1e3fc2e77a1.png)
Can't seem to replicate an overflow.
