### ISSUE TITLE
[Hacken 2022-11-25 High #2] Unverifiable Logic

### ISSUE THREAD

**Issue by zhongfu** [suberra/funnel-contracts#31]
The Funnel contract uses the functionality of the external *solmate* contracts, which are out of the scope and whose description states that it is an experimental software.

Therefore, their secureness may not be guaranteed, and their usage may lead to unexpected behavior.

## Path
./src/Funnel.sol : ERC20, SafeTransferLib

## Recommendation
Interact only with trusted contracts, validate results after calling outer contracts.

## Status
New

**Comment by zlace0x** [comment]
#49 Addresses this by replacing solmate with OZ
