### ISSUE TITLE
[Hacken 2022-11-25 Low #10] Functions that Can Be Declared External

### ISSUE THREAD

**Issue by zhongfu** [suberra/funnel-contracts#45]
In order to save Gas, `public` functions that are never called in the contract should be declared as `external`.

## Paths
./src/Funnel.sol : initialize(), permit(), permitRenewable(), approve(), approveRenewable(), allowance(), renewableAllowance(), supportsInterface()
./src/FunnelFactory.sol : deployFunnelForToken(), isFunnel()

## Recommendation
Use the external attribute for functions that are never called from the contract.

## Status
New

**Comment by edison0xyz** [comment]
Resolved in 3d75ccf5ebf499c13f0e0d88da5c452c06eb3f11
